// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: plugins/bakery.proto

package plugins

import (
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Bakery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled    *wrappers.BoolValue `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	BaseImages []*Bakery_BaseImage `protobuf:"bytes,2,rep,name=baseImages,proto3" json:"baseImages,omitempty"`
}

func (x *Bakery) Reset() {
	*x = Bakery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugins_bakery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bakery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bakery) ProtoMessage() {}

func (x *Bakery) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_bakery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bakery.ProtoReflect.Descriptor instead.
func (*Bakery) Descriptor() ([]byte, []int) {
	return file_plugins_bakery_proto_rawDescGZIP(), []int{0}
}

func (x *Bakery) GetEnabled() *wrappers.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

func (x *Bakery) GetBaseImages() []*Bakery_BaseImage {
	if x != nil {
		return x.BaseImages
	}
	return nil
}

type Bakery_BaseImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candidate string `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Unstable  string `protobuf:"bytes,2,opt,name=unstable,proto3" json:"unstable,omitempty"`
	Relase    string `protobuf:"bytes,3,opt,name=relase,proto3" json:"relase,omitempty"`
	Previous  string `protobuf:"bytes,4,opt,name=previous,proto3" json:"previous,omitempty"`
}

func (x *Bakery_BaseImage) Reset() {
	*x = Bakery_BaseImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugins_bakery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bakery_BaseImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bakery_BaseImage) ProtoMessage() {}

func (x *Bakery_BaseImage) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_bakery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bakery_BaseImage.ProtoReflect.Descriptor instead.
func (*Bakery_BaseImage) Descriptor() ([]byte, []int) {
	return file_plugins_bakery_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Bakery_BaseImage) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *Bakery_BaseImage) GetUnstable() string {
	if x != nil {
		return x.Unstable
	}
	return ""
}

func (x *Bakery_BaseImage) GetRelase() string {
	if x != nil {
		return x.Relase
	}
	return ""
}

func (x *Bakery_BaseImage) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

var File_plugins_bakery_proto protoreflect.FileDescriptor

var file_plugins_bakery_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x62, 0x61, 0x6b, 0x65, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x73, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfa, 0x01, 0x0a, 0x06, 0x42, 0x61, 0x6b, 0x65, 0x72, 0x79,
	0x12, 0x34, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x3f, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x42, 0x61, 0x6b, 0x65, 0x72,
	0x79, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x0a, 0x62, 0x61, 0x73,
	0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x79, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x65, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x6e, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x6c, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x6c, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f,
	0x75, 0x73, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x70, 0x69, 0x6e, 0x6e, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x6b, 0x6c, 0x65, 0x61, 0x74,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugins_bakery_proto_rawDescOnce sync.Once
	file_plugins_bakery_proto_rawDescData = file_plugins_bakery_proto_rawDesc
)

func file_plugins_bakery_proto_rawDescGZIP() []byte {
	file_plugins_bakery_proto_rawDescOnce.Do(func() {
		file_plugins_bakery_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugins_bakery_proto_rawDescData)
	})
	return file_plugins_bakery_proto_rawDescData
}

var file_plugins_bakery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugins_bakery_proto_goTypes = []interface{}{
	(*Bakery)(nil),             // 0: proto.plugins.Bakery
	(*Bakery_BaseImage)(nil),   // 1: proto.plugins.Bakery.BaseImage
	(*wrappers.BoolValue)(nil), // 2: google.protobuf.BoolValue
}
var file_plugins_bakery_proto_depIdxs = []int32{
	2, // 0: proto.plugins.Bakery.enabled:type_name -> google.protobuf.BoolValue
	1, // 1: proto.plugins.Bakery.baseImages:type_name -> proto.plugins.Bakery.BaseImage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plugins_bakery_proto_init() }
func file_plugins_bakery_proto_init() {
	if File_plugins_bakery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugins_bakery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bakery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugins_bakery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bakery_BaseImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugins_bakery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugins_bakery_proto_goTypes,
		DependencyIndexes: file_plugins_bakery_proto_depIdxs,
		MessageInfos:      file_plugins_bakery_proto_msgTypes,
	}.Build()
	File_plugins_bakery_proto = out.File
	file_plugins_bakery_proto_rawDesc = nil
	file_plugins_bakery_proto_goTypes = nil
	file_plugins_bakery_proto_depIdxs = nil
}
